nr = int(input('Digite um Nr : '))
print('-------------')
print(nr,' x 1 = {}'.format(nr*1))
print(nr,' x 2 = {}'.format(nr*2))
print(nr,' x 3 = {}'.format(nr*3))
print(nr,' x 4 = {}'.format(nr*4))
print(nr,' x 5 = {}'.format(nr*5))
print(nr,' x 6 = {}'.format(nr*6))
print(nr,' x 7 = {}'.format(nr*7))
print(nr,' x 8 = {}'.format(nr*8))
print(nr,' x 9 = {}'.format(nr*9))
print('--------------')